import { IState } from "./root"

export const state: IState = {
  // path: "C:/",
  currentNodeId: "2",
  sideBarMap: {
    "1": {
      id: "1",
      showChildren: true,
    },
    "2": {
      id: "2",
      showChildren: true,
    },
    "3": {
      id: "3",
      showChildren: false,
    },
  },
  flatMap: {
    "1": {
      id: "1",
      name: "C:",
      type: "dir",
      parentId: null,
      children: ["2"],
    },
    "2": {
      id: "2",
      name: "새폴더",
      type: "dir",
      parentId: "1",
      children: ["3"],
    },
    "3": {
      id: "3",
      name: "새폴더2",
      type: "dir",
      parentId: "2",
      children: null,
    },
  },
}
// {
//   path: "C:/",
//   flatMap: {
//     "1": {
//       id: "1",
//       name: "$Recycle.Bin",
//       type: "dir",
//       parentId: "root",
//       children: null,
//     },
//     "2": {
//       id: "2",
//       name: "$WinREAgent",
//       type: "dir",
//       parentId: "root",
//     },
//     "3": {
//       id: "3",
//       name: "%KLUCMD",
//       type: "dir",
//       parentId: "root",
//     },
//     "4": {
//       id: "4",
//       name: "9장",
//       type: "dir",
//       parentId: "root",
//     },
//     "5": {
//       id: "5",
//       name: "@$zjI",
//       type: "dir",
//       parentId: "root",
//     },
//     "6": {
//       id: "6",
//       name: "android",
//       type: "dir",
//       parentId: "root",
//     },
//     "7": {
//       id: "7",
//       name: "Bitnami",
//       type: "dir",
//       parentId: "root",
//     },
//     "8": {
//       id: "8",
//       name: "BUIS_HOME",
//       type: "dir",
//       parentId: "root",
//       children: [
//         {
//           id: "48",
//           name: "Bin",
//           type: "dir",
//           parentId: "8",
//         },
//         {
//           id: "49",
//           name: "Data",
//           type: "dir",
//           parentId: "8",
//         },
//         {
//           id: "50",
//           name: "Image",
//           type: "dir",
//           parentId: "8",
//         },
//         {
//           id: "51",
//           name: "Setup",
//           type: "dir",
//           parentId: "8",
//         },
//         {
//           id: "52",
//           name: "testFolder",
//           type: "dir",
//           parentId: "8",
//         },
//         {
//           id: "53",
//           name: "testFolder - 복사본",
//           type: "dir",
//           parentId: "8",
//         },
//         {
//           id: "54",
//           name: "testFolder - 복사본 (2)",
//           type: "dir",
//           parentId: "8",
//         },
//         {
//           id: "55",
//           name: "testFolder - 복사본 (3)",
//           type: "dir",
//           parentId: "8",
//         },
//         {
//           id: "56",
//           name: "testFolder - 복사본 (4)",
//           type: "dir",
//           parentId: "8",
//         },
//         {
//           id: "57",
//           name: "Work",
//           type: "dir",
//           parentId: "8",
//         },
//         {
//           id: "58",
//           name: "새 폴더",
//           type: "dir",
//           parentId: "8",
//         },
//       ],
//     },
//     "9": {
//       id: "9",
//       name: "ComboKey",
//       type: "dir",
//       parentId: "root",
//     },
//     "10": {
//       id: "10",
//       name: "Config.Msi",
//       type: "dir",
//       parentId: "root",
//     },
//     "11": {
//       id: "11",
//       name: "CrossEX.sig",
//       type: "file",
//       parentId: "root",
//     },
//     "12": {
//       id: "12",
//       name: "cypress-testbed",
//       type: "dir",
//       parentId: "root",
//     },
//     "13": {
//       id: "13",
//       name: "Documents and Settings",
//       type: "file",
//       parentId: "root",
//     },
//     "14": {
//       id: "14",
//       name: "DumpStack.log",
//       type: "file",
//       parentId: "root",
//     },
//     "15": {
//       id: "15",
//       name: "DumpStack.log.tmp",
//       type: "file",
//       parentId: "root",
//     },
//     "16": {
//       id: "16",
//       name: "ffmpeg-20200814-a762fd2-win64-static",
//       type: "dir",
//       parentId: "root",
//     },
//     "17": {
//       id: "17",
//       name: "gulp-test",
//       type: "dir",
//       parentId: "root",
//     },
//     "18": {
//       id: "18",
//       name: "hiberfil.sys",
//       type: "file",
//       parentId: "root",
//     },
//     "19": {
//       id: "19",
//       name: "immer",
//       type: "dir",
//       parentId: "root",
//     },
//     "20": {
//       id: "20",
//       name: "Intel",
//       type: "dir",
//       parentId: "root",
//     },
//     "21": {
//       id: "21",
//       name: "JS_pattern_test",
//       type: "dir",
//       parentId: "root",
//     },
//     "22": {
//       id: "22",
//       name: "JS_pattern_test - 복사본",
//       type: "dir",
//       parentId: "root",
//     },
//     "23": {
//       id: "23",
//       name: "JS_pattern_test - 복사본 (2)",
//       type: "dir",
//       parentId: "root",
//     },
//     "24": {
//       id: "24",
//       name: "JS_pattern_test - 복사본 (3)",
//       type: "dir",
//       parentId: "root",
//     },
//     "25": {
//       id: "25",
//       name: "JS_pattern_test - 복사본 (4)",
//       type: "dir",
//       parentId: "root",
//     },
//     "26": {
//       id: "26",
//       name: "kr.co.raon.touchenex.firefox.json",
//       type: "file",
//       parentId: "root",
//     },
//     "27": {
//       id: "27",
//       name: "kr.co.raon.touchenex.json",
//       type: "file",
//       parentId: "root",
//     },
//     "28": {
//       id: "28",
//       name: "multi-project",
//       type: "dir",
//       parentId: "root",
//     },
//     "29": {
//       id: "29",
//       name: "multiProjectTest",
//       type: "dir",
//       parentId: "root",
//     },
//     "30": {
//       id: "30",
//       name: "OneDriveTemp",
//       type: "dir",
//       parentId: "root",
//     },
//     "31": {
//       id: "31",
//       name: "pagefile.sys",
//       type: "file",
//       parentId: "root",
//     },
//     "32": {
//       id: "32",
//       name: "PerfLogs",
//       type: "dir",
//       parentId: "root",
//     },
//     "33": {
//       id: "33",
//       name: "Program Files",
//       type: "dir",
//       parentId: "root",
//     },
//     "34": {
//       id: "34",
//       name: "Program Files (x86)",
//       type: "dir",
//       parentId: "root",
//     },
//     "35": {
//       id: "35",
//       name: "ProgramData",
//       type: "dir",
//       parentId: "root",
//     },
//     "36": {
//       id: "36",
//       name: "Python310",
//       type: "dir",
//       parentId: "root",
//     },
//     "37": {
//       id: "37",
//       name: "Python38",
//       type: "dir",
//       parentId: "root",
//     },
//     "38": {
//       id: "38",
//       name: "Recovery",
//       type: "dir",
//       parentId: "root",
//     },
//     "39": {
//       id: "39",
//       name: "Riot Games",
//       type: "dir",
//       parentId: "root",
//     },
//     "40": {
//       id: "40",
//       name: "swapfile.sys",
//       type: "file",
//       parentId: "root",
//     },
//     "41": {
//       id: "41",
//       name: "System Volume Information",
//       type: "dir",
//       parentId: "root",
//     },
//     "42": {
//       id: "42",
//       name: "Temp",
//       type: "dir",
//       parentId: "root",
//     },
//     "43": {
//       id: "43",
//       name: "test.vsix",
//       type: "file",
//       parentId: "root",
//     },
//     "44": {
//       id: "44",
//       name: "testFolder",
//       type: "dir",
//       parentId: "root",
//     },
//     "45": {
//       id: "45",
//       name: "Users",
//       type: "dir",
//       parentId: "root",
//     },
//     "46": {
//       id: "46",
//       name: "Windows",
//       type: "dir",
//       parentId: "root",
//     },
//     "47": {
//       id: "47",
//       name: "_onDidChangeTreeData",
//       type: "dir",
//       parentId: "root",
//     },
//     "48": {
//       id: "48",
//       name: "Bin",
//       type: "dir",
//       parentId: "8",
//     },
//     "49": {
//       id: "49",
//       name: "Data",
//       type: "dir",
//       parentId: "8",
//     },
//     "50": {
//       id: "50",
//       name: "Image",
//       type: "dir",
//       parentId: "8",
//       children: [],
//     },
//     "51": {
//       id: "51",
//       name: "Setup",
//       type: "dir",
//       parentId: "8",
//       children: [
//         {
//           id: "59",
//           name: "BaekSeokManager.bat",
//           type: "file",
//           parentId: "51",
//         },
//         {
//           id: "60",
//           name: "BaekSeokManager.exe",
//           type: "file",
//           parentId: "51",
//         },
//         {
//           id: "61",
//           name: "IFUDD75.inf",
//           type: "file",
//           parentId: "51",
//         },
//         {
//           id: "62",
//           name: "Readme.txt",
//           type: "file",
//           parentId: "51",
//         },
//       ],
//     },
//     "52": {
//       id: "52",
//       name: "testFolder",
//       type: "dir",
//       parentId: "8",
//     },
//     "53": {
//       id: "53",
//       name: "testFolder - 복사본",
//       type: "dir",
//       parentId: "8",
//     },
//     "54": {
//       id: "54",
//       name: "testFolder - 복사본 (2)",
//       type: "dir",
//       parentId: "8",
//     },
//     "55": {
//       id: "55",
//       name: "testFolder - 복사본 (3)",
//       type: "dir",
//       parentId: "8",
//     },
//     "56": {
//       id: "56",
//       name: "testFolder - 복사본 (4)",
//       type: "dir",
//       parentId: "8",
//     },
//     "57": {
//       id: "57",
//       name: "Work",
//       type: "dir",
//       parentId: "8",
//     },
//     "58": {
//       id: "58",
//       name: "새 폴더",
//       type: "dir",
//       parentId: "8",
//     },
//     "59": {
//       id: "59",
//       name: "BaekSeokManager.bat",
//       type: "file",
//       parentId: "51",
//     },
//     "60": {
//       id: "60",
//       name: "BaekSeokManager.exe",
//       type: "file",
//       parentId: "51",
//     },
//     "61": {
//       id: "61",
//       name: "IFUDD75.inf",
//       type: "file",
//       parentId: "51",
//     },
//     "62": {
//       id: "62",
//       name: "Readme.txt",
//       type: "file",
//       parentId: "51",
//     },
//     root: {
//       id: "root",
//       name: "C:/",
//       type: "dir",
//       parentId: null,
//       children: [
//         {
//           id: "1",
//           name: "$Recycle.Bin",
//           type: "dir",
//           parentId: "root",
//         },
//         {
//           id: "2",
//           name: "$WinREAgent",
//           type: "dir",
//           parentId: "root",
//         },
//         {
//           id: "3",
//           name: "%KLUCMD",
//           type: "dir",
//           parentId: "root",
//         },
//         {
//           id: "4",
//           name: "9장",
//           type: "dir",
//           parentId: "root",
//         },
//         {
//           id: "5",
//           name: "@$zjI",
//           type: "dir",
//           parentId: "root",
//         },
//         {
//           id: "6",
//           name: "android",
//           type: "dir",
//           parentId: "root",
//         },
//         {
//           id: "7",
//           name: "Bitnami",
//           type: "dir",
//           parentId: "root",
//         },
//         {
//           id: "8",
//           name: "BUIS_HOME",
//           type: "dir",
//           parentId: "root",
//         },
//         {
//           id: "9",
//           name: "ComboKey",
//           type: "dir",
//           parentId: "root",
//         },
//         {
//           id: "10",
//           name: "Config.Msi",
//           type: "dir",
//           parentId: "root",
//         },
//         {
//           id: "11",
//           name: "CrossEX.sig",
//           type: "file",
//           parentId: "root",
//         },
//         {
//           id: "12",
//           name: "cypress-testbed",
//           type: "dir",
//           parentId: "root",
//         },
//         {
//           id: "13",
//           name: "Documents and Settings",
//           type: "file",
//           parentId: "root",
//         },
//         {
//           id: "14",
//           name: "DumpStack.log",
//           type: "file",
//           parentId: "root",
//         },
//         {
//           id: "15",
//           name: "DumpStack.log.tmp",
//           type: "file",
//           parentId: "root",
//         },
//         {
//           id: "16",
//           name: "ffmpeg-20200814-a762fd2-win64-static",
//           type: "dir",
//           parentId: "root",
//         },
//         {
//           id: "17",
//           name: "gulp-test",
//           type: "dir",
//           parentId: "root",
//         },
//         {
//           id: "18",
//           name: "hiberfil.sys",
//           type: "file",
//           parentId: "root",
//         },
//         {
//           id: "19",
//           name: "immer",
//           type: "dir",
//           parentId: "root",
//         },
//         {
//           id: "20",
//           name: "Intel",
//           type: "dir",
//           parentId: "root",
//         },
//         {
//           id: "21",
//           name: "JS_pattern_test",
//           type: "dir",
//           parentId: "root",
//         },
//         {
//           id: "22",
//           name: "JS_pattern_test - 복사본",
//           type: "dir",
//           parentId: "root",
//         },
//         {
//           id: "23",
//           name: "JS_pattern_test - 복사본 (2)",
//           type: "dir",
//           parentId: "root",
//         },
//         {
//           id: "24",
//           name: "JS_pattern_test - 복사본 (3)",
//           type: "dir",
//           parentId: "root",
//         },
//         {
//           id: "25",
//           name: "JS_pattern_test - 복사본 (4)",
//           type: "dir",
//           parentId: "root",
//         },
//         {
//           id: "26",
//           name: "kr.co.raon.touchenex.firefox.json",
//           type: "file",
//           parentId: "root",
//         },
//         {
//           id: "27",
//           name: "kr.co.raon.touchenex.json",
//           type: "file",
//           parentId: "root",
//         },
//         {
//           id: "28",
//           name: "multi-project",
//           type: "dir",
//           parentId: "root",
//         },
//         {
//           id: "29",
//           name: "multiProjectTest",
//           type: "dir",
//           parentId: "root",
//         },
//         {
//           id: "30",
//           name: "OneDriveTemp",
//           type: "dir",
//           parentId: "root",
//         },
//         {
//           id: "31",
//           name: "pagefile.sys",
//           type: "file",
//           parentId: "root",
//         },
//         {
//           id: "32",
//           name: "PerfLogs",
//           type: "dir",
//           parentId: "root",
//         },
//         {
//           id: "33",
//           name: "Program Files",
//           type: "dir",
//           parentId: "root",
//         },
//         {
//           id: "34",
//           name: "Program Files (x86)",
//           type: "dir",
//           parentId: "root",
//         },
//         {
//           id: "35",
//           name: "ProgramData",
//           type: "dir",
//           parentId: "root",
//         },
//         {
//           id: "36",
//           name: "Python310",
//           type: "dir",
//           parentId: "root",
//         },
//         {
//           id: "37",
//           name: "Python38",
//           type: "dir",
//           parentId: "root",
//         },
//         {
//           id: "38",
//           name: "Recovery",
//           type: "dir",
//           parentId: "root",
//         },
//         {
//           id: "39",
//           name: "Riot Games",
//           type: "dir",
//           parentId: "root",
//         },
//         {
//           id: "40",
//           name: "swapfile.sys",
//           type: "file",
//           parentId: "root",
//         },
//         {
//           id: "41",
//           name: "System Volume Information",
//           type: "dir",
//           parentId: "root",
//         },
//         {
//           id: "42",
//           name: "Temp",
//           type: "dir",
//           parentId: "root",
//         },
//         {
//           id: "43",
//           name: "test.vsix",
//           type: "file",
//           parentId: "root",
//         },
//         {
//           id: "44",
//           name: "testFolder",
//           type: "dir",
//           parentId: "root",
//         },
//         {
//           id: "45",
//           name: "Users",
//           type: "dir",
//           parentId: "root",
//         },
//         {
//           id: "46",
//           name: "Windows",
//           type: "dir",
//           parentId: "root",
//         },
//         {
//           id: "47",
//           name: "_onDidChangeTreeData",
//           type: "dir",
//           parentId: "root",
//         },
//       ],
//     },
//   },
// }
